language: bash
env:
  - LC_ALL=""
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y smokeping
script: smokeping --check --config /home/travis/Freifunk-Troisdorf/smokeping-config/config
