language: bash
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y smokeping
install: 
  - wget http://oss.oetiker.ch/smokeping/pub/smokeping-2.6.8.tar.gz
  - tar -xzvf smokeping-2.6.8.tar.gz
  - cd smokeping-2.6.8 && ./configure --prefix=/home/travis/build/Freifunk-Troisdorf/smokeping-config/smokeping && make install
script: /usr/sbin/dhcpd -t -cf ./static-dhcp/dhcpd.conf
